### ISSUE TITLE
第二次会议记录

### ISSUE THREAD

**Issue by shinyypig** [HFUT-DSP/Pedestrian_Detection_System#2]
## 会议内容

1. 接口规划与功能设计详细解读
本段内容主要讲述了接口规划方面的工作，包括系统功能设计、软件架构设计、系统终端设计、用户登录功能等。同时，还提到了一些具体的实现细节，如用户登录界面、表单设计、数据库表设计等。
1. 前后端协作与任务分配的讨论
主要讲述了前后端分工协作的工作方式。前端和后端各自负责不同的任务，如用户登录、用户列表维护等。前端主要负责界面设计，后端则负责数据操作。在实际工作中，可以先完成一个模块的设计，然后根据实际情况进行调整。此外，还可以在开发过程中与前后端同学沟通，共同解决问题。最后，提醒大家找一些开源的Java Web框架，以便在基础上进行修改。
1. 开源框架使用与团队分工讨论
会议讨论了开源框架的使用、分工和任务分配。首先，找到一个开源框架，并确定具体任务。然后，根据各自擅长的部分进行分工，遇到问题时可以协商讨论。接下来讨论了代码托管和组织建设的问题，最后决定建立一个组织，并将其作为实验室的主号。最后，还提到了将文档转换为Markdown的问题。
1. 团队协作与任务分配的讨论
讨论工作内容，包括前端和后端的共同任务，以及如何与后端沟通。提到用户登录涉及到前端和后端，需要共同完成。前端主要负责展示，后端负责处理数据。还讨论了接口类型和数据输入方式，建议参照现有的开源代码。最后决定在实际编写代码时，可以通过假接口进行调试。
1. 项目管理与团队协作的实践
主要讨论了项目开发和代码管理的问题。首先，会议提到了用户登录功能和用户管理功能的实现，以及如何将任务拆分为具体的功能模块。其次，讨论了如何进行代码管理和团队协作，包括分配任务、提、审核等。最后，会议还提到了一些具体的操作步骤，如编写会议纪要、找开源资源等。

## 会议待办

1. 在会议中补充设计文档中的部分内容，以便更好地了解项目需求和功能
1. 确定前端和后端的任务分工，以便更好地完成系统开发
1. 找到开源框架并分配具体任务落实到每个人，以便更好地完成项目
1. 下周会议，初步了解项目进展情况以便提出意见
1. 学习并熟悉git的使用以更好地进行代码提交和项目管理

## 首周任务分配

1. 用户登陆：
    - 后端：涂玉华，裴跃
    - 前端：朱子建

1. 用户列表维护：
    - 后端：彭景，王静
    - 前端：兰翔

**Comment by master12454** [comment]
首周任务分配
• 用户登陆：
后端：涂玉华，裴跃
前端：朱子建

• 用户列表维护：
后端：彭景，王静
前端：兰翔

**Comment by shinyypig** [comment]
> 首周任务分配 • 用户登陆： 后端：涂玉华，裴跃 前端：朱子建
> 
> • 用户列表维护： 后端：彭景，王静 前端：兰翔

可以直接修改我提交的部分，我已经合并进去了；此外，不妨看一下markdown语法。
