### ISSUE TITLE
关于目前框架能够调用行人识别后端的问题

### ISSUE THREAD

**Issue by shinyypig** [HFUT-DSP/Pedestrian_Detection_System#9]
进行如下测试：

1. 用python写一个视频流读取的代码
1. 用java实时接收数据
1. 在web上播放

如果不能或实现难度大，需尽快更换框架，有问题在本 issue 反馈。

> 备用选项 Django + Vue, 教程 https://dev.to/huericnan/create-a-modern-application-with-django-and-vue-242j

**Comment by lanxiang224** [comment]
#### 测试方案：

1. python部分使用OpenCV读取视频帧，使用Flask框架提供视频流。

   涉及关键代码：

   ```
   # Flask 服务器将从本地读取视频流，并在 http://localhost:5000/video_feed 提供视频流
   app.run(host='0.0.0.0', port=5000) 
   ```

2. JavaWeb部分创建一个Web应用，通过一个HTML页面显示来自Python服务器的视频流。

   涉及关键代码：

   ```
   # 前端页面
   <img src="http://localhost:5000/video_feed" width="640" height="480" />
   ```

该方案由前端页面直接向Flask服务器请求视频流，实时性较高。若有需求可以让Flask将视频帧同时发送到 Java 服务器，这样既能在前端实时显示视频又能在后端存储视频帧。

方案经过编码测试已成功实现。
